config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [ :index ], path: "" do
    collection do
      get :about
      post :forecast
      post :metric
      post :imperial
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"

  get "*path", to: redirect("/")
end

app/models/forecast.rb
# frozen_string_literal: true

# This class represents a weather forecast
class Forecast < ApplicationRecord
  belongs_to :city, counter_cache: :forecasts_count

  has_many :days, dependent: :destroy

  validates :city_id, presence: true

  scope :for_city, ->(city) { joins(:city).where(cities: { name: city }) if city.present? }
  scope :for_region, ->(region) { joins(:city).where(cities: { region: region }) if region.present? }

  def cached_at
    Time.now
  end

  # Does the forecast need to be refreshed?
  # @return [Boolean] true if the forecast needs to be refreshed, false otherwise
  # @note The forecast is considered stale if the condition is blank or if it was last updated more than the configured refresh interval.
  # @example
  #   if forecast.refresh?
  #     forecast.refresh!
  #   end
  def refresh?
    condition.blank? || updated_at < Settings.forecast_refresh_in.ago
  end

  # Refresh the forecast data from the weather API
  # @note This method iterates through the configured forecast services and fetches the data for the specified city and region.
  def refresh!
    Settings.forecast_services.each do |service_name|
      service_class = service_name.camelize.constantize
      service_instance = service_class.new(city: city.name, region: city.region, units: units)
      attributes = service_instance.call
      if attributes.present?
        attributes.each do |key, value|
          if key == :days
            refresh_days(value)
          elsif self.respond_to?(key)
            self[key] = value
          end
        end
        self.save
        break
      end
    end
    self.reload
  end

  private

  def refresh_days(days_data)
    if days.present?
      days.destroy_all
    end
    if days_data.present?
      days_data.each do |day_data|
        day = days.find_or_create_by(date: day_data[:date], units: units)
        day.update(day_data)
      end
    end
  end
end

app/views/pages/forecast/_day.html.erb
<% day_presenter = DayPresenter.new(day) %>
<div class="col">
  <div class="card mb-4">
    <div class="card-header">
      <h6><%= format_date(day.date) %></h6>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <p class="fs-5 my-2">
          <%= day_presenter.condition %>
        </p>
      </li>
      <li class="list-group-item">
        <p class="fs-5 my-2">
          <%= day_presenter.min_temp %> / <%= day_presenter.max_temp %>
        </p>
      </li>
    </ul>
  </div>
</div>

app/views/pages/forecast/_field.html.erb
<div class="col">
  <div class="card mb-4">
    <div class="card-header">
      <h6><%= label %></h6>
    </div>
    <div class="card-body">
      <%= field_value(label, value) %>
    </div>
  </div>
</div>

app/views/pages/forecast/_form.html.erb
<% location ||= @location %>
<div class="p-5 mb-4 bg-body-tertiary rounded-3" data-controller="geocode">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">How's the weather?</h1>
    <p class="col-md-8 fs-4">Hmm, will I need an umbrella or sunscreen today...</p>
    <%= form_tag forecast_pages_path, class: "mb-3", data: { geocode_target: "form", turbo_frame: 'forecast_results' } do %>
    <%= hidden_field_tag :latitude, "", data: { geocode_target: "latitude" } %>
    <%= hidden_field_tag :longitude, "", data: { geocode_target: "longitude" } %>
    <div class="input-group">
      <%= text_field_tag :location, location, class: "form-control form-control-lg", placeholder: "Enter your location...", data: { geocode_target: "address" } %>
      <button class="btn btn-outline-primary" type="button" id="locate" title="Locate me" data-action="click->geocode#locate">
        <i class="bi bi-geo-alt"></i>
      </button>
      <button class="btn btn-outline-primary" type="submit" id="search" title="Search">
        <i class="bi bi-search"></i>
      </button>
    </div>
    <% end %>
    <p class="text-secondary" data-geocode-target="info"></p>
    <p class="text-danger" data-geocode-target="error"></p>
  </div>
</div>

app/views/pages/forecast/_results.html.erb
<% forecast ||= @forecast %>
<%= turbo_frame_tag 'forecast_results' do %>
<% if forecast.blank? %>
<div id="loading" class="text-center text-muted my-5 d-none">
  <%= image_tag "spinner.svg" %> Loading...
</div>
<% elsif forecast.valid? %>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
  <% ForecastPresenter.new(forecast).fields.each do |label, value| %>
  <%= render 'pages/forecast/field', label: label, value: value %>
  <% end %>
  <% forecast.days.each do |day| %>
  <%= render 'pages/forecast/day', day: day %>
  <% end %>
</div>
<% else %>
<div class="alert alert-warning" role="alert">
  There was a problem loading the forecast for that location, please try again.
</div>
<% end %>
<% end %>