config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [ :index ], path: "" do
    collection do
      get :about
      post :forecast
      post :metric
      post :imperial
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"

  get "*path", to: redirect("/")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :metric?, :imperial?, :current_units

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # The user's current units, either metric or imperial.
  # @return [String] the current units, either 'metric' or 'imperial'.
  # @note Defaults to the value set in the Rails configuration.
  # @see Rails.configuration.x.default_units
  # @see Rails.configuration.x.units
  def current_units
    @current_units ||= cookies[:units] || Settings.default_units.to_s
  end

  # Is the current units metric?
  # @return [Boolean] true if the current units are metric, false otherwise.
  # @see Rails.configuration.x.units
  # @see #current_units
  # @example
  #   if metric?
  #     # Do something for metric units
  #   else
  #     # Do something for imperial units
  #   end
  # @note This method checks the current units against the metric units defined in the Rails configuration.
  def metric?
    current_units == Settings.metric_name
  end

  # Is the current units imperial?
  # @return [Boolean] true if the current units are imperial, false otherwise.
  # @see Rails.configuration.x.units
  # @see #current_units
  # @example
  #   if imperial?
  #     # Do something for imperial units
  #   else
  #     # Do something for metric units
  #   end
  # @note This method checks the current units against the imperial units defined in the Rails configuration.
  def imperial?
    current_units == Settings.imperial_name
  end

  # Set the current units in the cookies.
  # @param units [String] the units to set, either 'metric' or 'imperial'.
  # @note This method sets the units in the cookies for persistence across requests.
  def set_units(units)
    @current_units = cookies[:units] = units
  end

  # Set the current units to metric
  # @note This method sets the units to metric in the cookies for persistence across requests.
  def set_units_metric
    set_units(Settings.metric_name)
  end

  # Set the current units to imperial
  # @note This method sets the units to imperial in the cookies for persistence across requests.
  def set_units_imperial
    set_units(Settings.imperial_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the site title
  # @return [String] the site title
  def site_title
    Settings.site_title
  end

  # Returns the site description
  # @return [String] the site description
  def site_description
    Settings.site_description
  end

  # Returns the site URL
  # @return [String] the site URL
  def site_url
    Settings.site_url
  end

  # Returns the site source code URL
  # @return [String] the site source code URL
  def site_source
    Settings.site_source
  end

  # Returns the page or site title
  # @return [String] the page or site title
  def page_title
    content_for(:title) || site_title
  end

  # Returns the page or site description
  # @return [String] the page or site description
  def page_description
    content_for(:description) || site_description
  end

  # Returns the page or site URL
  # @return [String] the page or site URL
  def page_url
    content_for(:url) || site_url
  end

  # Returns label for metric units
  # @return [String] the label for metric units
  def metric_label
    Settings.metric_label
  end

  # Returns label for imperial units
  # @return [String] the label for imperial units
  def imperial_label
    Settings.imperial_label
  end

  # Returns the appropriate class for flash messages
  # @param level [Symbol] the flash message level (e.g., :notice, :alert, :success)
  # @return [String] the CSS class for the flash message
  def flash_class(level)
    case level.to_sym
    when :notice
      "info"
    when :alert
      "danger"
    when :success
      "success"
    else
      "secondary"
    end
  end

  # Returns 'active' class if the current action matches the given path
  # @param path [String] the path to check against the current action
  # @return [String] 'active' if the current action matches the path, nil otherwise
  def active_for_path(path)
    "active" if params[:action] == path
  end

  # Returns the appropriate field value based on the label and value
  # @param label [String] the label of the field
  # @param value [String] the value of the field
  # @return [String] the formatted field value
  # @note If the value is blank, returns "n/a". If the label is 'Updated' or 'Cached', returns a time ago string.
  def field_value(label, value)
    if value.blank?
      content_tag(:p, class: "fs-5 my-2") do
        "n/a"
      end
    elsif label == "Current"
      image_tag(value, alt: "Weather Icon", class: "img-icon") unless value.blank?
    elsif %w[Updated Cached].include?(label)
      content_tag(:p, class: "fs-5 my-2") do
        time_ago_in_words(value) + " ago"
      end
    else
      content_tag(:p, class: "fs-5 my-2") do
        value.to_s
      end
    end
  end

  # Returns the formatted date string
  # @param date [Date, Time] the date to format
  # @return [String] the formatted date string
  # @note If the date is blank, returns nil. The format is 'Day, Month Day' with a suffix for the day.
  def format_date(date)
    return if date.blank?

    date = date.to_date
    date.strftime("%A, %B %-d") + day_suffix(date.day)
  end

  # Returns the appropriate suffix for the day of the month
  # @param day [Integer] the day of the month
  # @return [String] the suffix for the day of the month
  # @note The suffixes are 'st', 'nd', 'rd', and 'th' based on the day of the month.
  def day_suffix(day)
    case day
    when 1, 21, 31
      "st"
    when 2, 22
      "nd"
    when 3, 23
      "rd"
    else
      "th"
    end
  end
end

app/views/application/_flash.html.erb
<% if flash.any? %>
<% flash.each do |key, value| %>
<div class="alert alert-<%= flash_class(key) %> alert-dismissible fade show mt-4" role="alert">
  <span><%= value %></span>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded">
  <div class="container-fluid">
    <%= link_to "iWeather", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_pages_path, class: "nav-link #{active_for_path('about')}" %>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0 ml-auto">
        <li class="ms-auto nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= metric? ? metric_label : imperial_label %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <%= button_to metric_label, metric_pages_path, method: :post, class: "dropdown-item #{'active' if metric?}" %>
            </li>
            <li>
              <%= button_to imperial_label, imperial_pages_path, method: :post, class: "dropdown-item #{'active' if imperial?}" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>